# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/maryna/Documents/nta/integer_factorization

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/maryna/Documents/nta/integer_factorization

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/maryna/Documents/nta/integer_factorization/CMakeFiles /home/maryna/Documents/nta/integer_factorization//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/maryna/Documents/nta/integer_factorization/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named td_test

# Build rule for target.
td_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 td_test
.PHONY : td_test

# fast build rule for target.
td_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/td_test.dir/build.make CMakeFiles/td_test.dir/build
.PHONY : td_test/fast

#=============================================================================
# Target rules for targets named qs_test

# Build rule for target.
qs_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qs_test
.PHONY : qs_test

# fast build rule for target.
qs_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qs_test.dir/build.make CMakeFiles/qs_test.dir/build
.PHONY : qs_test/fast

#=============================================================================
# Target rules for targets named factor_main

# Build rule for target.
factor_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 factor_main
.PHONY : factor_main

# fast build rule for target.
factor_main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/factor_main.dir/build.make CMakeFiles/factor_main.dir/build
.PHONY : factor_main/fast

#=============================================================================
# Target rules for targets named long_modular_arithmetic

# Build rule for target.
long_modular_arithmetic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 long_modular_arithmetic
.PHONY : long_modular_arithmetic

# fast build rule for target.
long_modular_arithmetic/fast:
	$(MAKE) $(MAKESILENT) -f long_modular_arithmetic/CMakeFiles/long_modular_arithmetic.dir/build.make long_modular_arithmetic/CMakeFiles/long_modular_arithmetic.dir/build
.PHONY : long_modular_arithmetic/fast

main/main.o: main/main.cpp.o
.PHONY : main/main.o

# target to build an object file
main/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/factor_main.dir/build.make CMakeFiles/factor_main.dir/main/main.cpp.o
.PHONY : main/main.cpp.o

main/main.i: main/main.cpp.i
.PHONY : main/main.i

# target to preprocess a source file
main/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/factor_main.dir/build.make CMakeFiles/factor_main.dir/main/main.cpp.i
.PHONY : main/main.cpp.i

main/main.s: main/main.cpp.s
.PHONY : main/main.s

# target to generate assembly for a file
main/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/factor_main.dir/build.make CMakeFiles/factor_main.dir/main/main.cpp.s
.PHONY : main/main.cpp.s

src/f_exeption.o: src/f_exeption.cpp.o
.PHONY : src/f_exeption.o

# target to build an object file
src/f_exeption.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qs_test.dir/build.make CMakeFiles/qs_test.dir/src/f_exeption.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/factor_main.dir/build.make CMakeFiles/factor_main.dir/src/f_exeption.cpp.o
.PHONY : src/f_exeption.cpp.o

src/f_exeption.i: src/f_exeption.cpp.i
.PHONY : src/f_exeption.i

# target to preprocess a source file
src/f_exeption.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qs_test.dir/build.make CMakeFiles/qs_test.dir/src/f_exeption.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/factor_main.dir/build.make CMakeFiles/factor_main.dir/src/f_exeption.cpp.i
.PHONY : src/f_exeption.cpp.i

src/f_exeption.s: src/f_exeption.cpp.s
.PHONY : src/f_exeption.s

# target to generate assembly for a file
src/f_exeption.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qs_test.dir/build.make CMakeFiles/qs_test.dir/src/f_exeption.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/factor_main.dir/build.make CMakeFiles/factor_main.dir/src/f_exeption.cpp.s
.PHONY : src/f_exeption.cpp.s

src/matrix.o: src/matrix.cpp.o
.PHONY : src/matrix.o

# target to build an object file
src/matrix.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qs_test.dir/build.make CMakeFiles/qs_test.dir/src/matrix.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/factor_main.dir/build.make CMakeFiles/factor_main.dir/src/matrix.cpp.o
.PHONY : src/matrix.cpp.o

src/matrix.i: src/matrix.cpp.i
.PHONY : src/matrix.i

# target to preprocess a source file
src/matrix.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qs_test.dir/build.make CMakeFiles/qs_test.dir/src/matrix.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/factor_main.dir/build.make CMakeFiles/factor_main.dir/src/matrix.cpp.i
.PHONY : src/matrix.cpp.i

src/matrix.s: src/matrix.cpp.s
.PHONY : src/matrix.s

# target to generate assembly for a file
src/matrix.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qs_test.dir/build.make CMakeFiles/qs_test.dir/src/matrix.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/factor_main.dir/build.make CMakeFiles/factor_main.dir/src/matrix.cpp.s
.PHONY : src/matrix.cpp.s

src/quadratic_sieve.o: src/quadratic_sieve.cpp.o
.PHONY : src/quadratic_sieve.o

# target to build an object file
src/quadratic_sieve.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qs_test.dir/build.make CMakeFiles/qs_test.dir/src/quadratic_sieve.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/factor_main.dir/build.make CMakeFiles/factor_main.dir/src/quadratic_sieve.cpp.o
.PHONY : src/quadratic_sieve.cpp.o

src/quadratic_sieve.i: src/quadratic_sieve.cpp.i
.PHONY : src/quadratic_sieve.i

# target to preprocess a source file
src/quadratic_sieve.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qs_test.dir/build.make CMakeFiles/qs_test.dir/src/quadratic_sieve.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/factor_main.dir/build.make CMakeFiles/factor_main.dir/src/quadratic_sieve.cpp.i
.PHONY : src/quadratic_sieve.cpp.i

src/quadratic_sieve.s: src/quadratic_sieve.cpp.s
.PHONY : src/quadratic_sieve.s

# target to generate assembly for a file
src/quadratic_sieve.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qs_test.dir/build.make CMakeFiles/qs_test.dir/src/quadratic_sieve.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/factor_main.dir/build.make CMakeFiles/factor_main.dir/src/quadratic_sieve.cpp.s
.PHONY : src/quadratic_sieve.cpp.s

src/solovay_strassen.o: src/solovay_strassen.cpp.o
.PHONY : src/solovay_strassen.o

# target to build an object file
src/solovay_strassen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qs_test.dir/build.make CMakeFiles/qs_test.dir/src/solovay_strassen.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/factor_main.dir/build.make CMakeFiles/factor_main.dir/src/solovay_strassen.cpp.o
.PHONY : src/solovay_strassen.cpp.o

src/solovay_strassen.i: src/solovay_strassen.cpp.i
.PHONY : src/solovay_strassen.i

# target to preprocess a source file
src/solovay_strassen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qs_test.dir/build.make CMakeFiles/qs_test.dir/src/solovay_strassen.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/factor_main.dir/build.make CMakeFiles/factor_main.dir/src/solovay_strassen.cpp.i
.PHONY : src/solovay_strassen.cpp.i

src/solovay_strassen.s: src/solovay_strassen.cpp.s
.PHONY : src/solovay_strassen.s

# target to generate assembly for a file
src/solovay_strassen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qs_test.dir/build.make CMakeFiles/qs_test.dir/src/solovay_strassen.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/factor_main.dir/build.make CMakeFiles/factor_main.dir/src/solovay_strassen.cpp.s
.PHONY : src/solovay_strassen.cpp.s

src/trial_division.o: src/trial_division.cpp.o
.PHONY : src/trial_division.o

# target to build an object file
src/trial_division.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/td_test.dir/build.make CMakeFiles/td_test.dir/src/trial_division.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qs_test.dir/build.make CMakeFiles/qs_test.dir/src/trial_division.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/factor_main.dir/build.make CMakeFiles/factor_main.dir/src/trial_division.cpp.o
.PHONY : src/trial_division.cpp.o

src/trial_division.i: src/trial_division.cpp.i
.PHONY : src/trial_division.i

# target to preprocess a source file
src/trial_division.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/td_test.dir/build.make CMakeFiles/td_test.dir/src/trial_division.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qs_test.dir/build.make CMakeFiles/qs_test.dir/src/trial_division.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/factor_main.dir/build.make CMakeFiles/factor_main.dir/src/trial_division.cpp.i
.PHONY : src/trial_division.cpp.i

src/trial_division.s: src/trial_division.cpp.s
.PHONY : src/trial_division.s

# target to generate assembly for a file
src/trial_division.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/td_test.dir/build.make CMakeFiles/td_test.dir/src/trial_division.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qs_test.dir/build.make CMakeFiles/qs_test.dir/src/trial_division.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/factor_main.dir/build.make CMakeFiles/factor_main.dir/src/trial_division.cpp.s
.PHONY : src/trial_division.cpp.s

test/qs_test.o: test/qs_test.cpp.o
.PHONY : test/qs_test.o

# target to build an object file
test/qs_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qs_test.dir/build.make CMakeFiles/qs_test.dir/test/qs_test.cpp.o
.PHONY : test/qs_test.cpp.o

test/qs_test.i: test/qs_test.cpp.i
.PHONY : test/qs_test.i

# target to preprocess a source file
test/qs_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qs_test.dir/build.make CMakeFiles/qs_test.dir/test/qs_test.cpp.i
.PHONY : test/qs_test.cpp.i

test/qs_test.s: test/qs_test.cpp.s
.PHONY : test/qs_test.s

# target to generate assembly for a file
test/qs_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qs_test.dir/build.make CMakeFiles/qs_test.dir/test/qs_test.cpp.s
.PHONY : test/qs_test.cpp.s

test/td_test.o: test/td_test.cpp.o
.PHONY : test/td_test.o

# target to build an object file
test/td_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/td_test.dir/build.make CMakeFiles/td_test.dir/test/td_test.cpp.o
.PHONY : test/td_test.cpp.o

test/td_test.i: test/td_test.cpp.i
.PHONY : test/td_test.i

# target to preprocess a source file
test/td_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/td_test.dir/build.make CMakeFiles/td_test.dir/test/td_test.cpp.i
.PHONY : test/td_test.cpp.i

test/td_test.s: test/td_test.cpp.s
.PHONY : test/td_test.s

# target to generate assembly for a file
test/td_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/td_test.dir/build.make CMakeFiles/td_test.dir/test/td_test.cpp.s
.PHONY : test/td_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... factor_main"
	@echo "... long_modular_arithmetic"
	@echo "... qs_test"
	@echo "... td_test"
	@echo "... main/main.o"
	@echo "... main/main.i"
	@echo "... main/main.s"
	@echo "... src/f_exeption.o"
	@echo "... src/f_exeption.i"
	@echo "... src/f_exeption.s"
	@echo "... src/matrix.o"
	@echo "... src/matrix.i"
	@echo "... src/matrix.s"
	@echo "... src/quadratic_sieve.o"
	@echo "... src/quadratic_sieve.i"
	@echo "... src/quadratic_sieve.s"
	@echo "... src/solovay_strassen.o"
	@echo "... src/solovay_strassen.i"
	@echo "... src/solovay_strassen.s"
	@echo "... src/trial_division.o"
	@echo "... src/trial_division.i"
	@echo "... src/trial_division.s"
	@echo "... test/qs_test.o"
	@echo "... test/qs_test.i"
	@echo "... test/qs_test.s"
	@echo "... test/td_test.o"
	@echo "... test/td_test.i"
	@echo "... test/td_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

